### ISSUE TITLE
Request: php-pecl-ssh2

### ISSUE THREAD

**Issue by kkavchakHT** [iusrepo/php73#19]
I have run into an issue with this showing in the log file: 
> PHP Fatal error:  Uncaught Error: Call to undefined function ssh2_connect() 

Based on an answer [here](https://stackoverflow.com/questions/18979144/call-to-undefined-function-ssh2-connect), it should be able to be resolved by running
`yum install php-pecl-ssh2`

The package is not available in the IUS repo, so this results in it trying to install another version and failing:
```
Resolving Dependencies
--> Running transaction check
---> Package php-pecl-ssh2.x86_64 0:0.12-1.el7 will be installed
--> Processing Dependency: php(zend-abi) = 20100525-64 for package: php-pecl-ssh2-0.12-1.el7.x86_64
--> Processing Dependency: php(api) = 20100412-64 for package: php-pecl-ssh2-0.12-1.el7.x86_64
--> Running transaction check
---> Package php-common.x86_64 0:5.4.16-48.el7 will be installed
--> Processing Conflict: php73-common-7.3.17-1.el7.ius.x86_64 conflicts php-common < 7.3.17-1.el7.ius
--> Processing Conflict: php73-json-7.3.17-1.el7.ius.x86_64 conflicts php-json < 7.3.17-1.el7.ius
--> Finished Dependency Resolution
Error: php73-common conflicts with php-common-5.4.16-48.el7.x86_64
Error: php73-json conflicts with php-common-5.4.16-48.el7.x86_64
 You could try using --skip-broken to work around the problem
 You could try running: rpm -Va --nofiles --nodigest
```

**Comment by carlwgeorge** [comment]
When you run `yum install php-pecl-ssh2`, you are asking yum to install that exact package, which is from EPEL.  IUS doesn't ship packages with the same names as stock or EPEL packages by design.  The EPEL package is specifically built to be compatible with the stock version of php (5.4).  You can read more about how IUS packages work at the following links.

* https://ius.io/about
* https://ius.io/usage

If you would like to request a php73-pecl-ssh2 package, there is a "request new package" button on our [homepage](https://ius.io).
